// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_write   5
#define SYS_read    6
#define SYS_close   7
#define SYS_kill    8
#define SYS_exec    9
#define SYS_open   10
#define SYS_mknod  11
#define SYS_unlink 12
#define SYS_fstat  13
#define SYS_link   14
#define SYS_mkdir  15
#define SYS_chdir  16
#define SYS_dup    17
#define SYS_getpid 18
#define SYS_sbrk   19
#define SYS_sleep  20
#define SYS_uptime 21
#define SYS_thread_create 22
#define SYS_thread_getid 23
#define SYS_thread_getProcid 24
#define SYS_thread_join 25
#define SYS_thread_exit 26
#define SYS_binary_sem_create 27
#define SYS_binary_sem_down 28
#define SYS_binary_sem_up 29
#define SYS_binary_sem_clear 30
#define SYS_exit_all_threads 31